remote_theme: APIDevTools/gh-pages-theme

title: OpenAPI Specification Schemas
logo: https://apidevtools.org/img/logos/logo.png

author:
  twitter: APIDevTools

google_analytics: UA-68102273-3

twitter:
  username: APIDevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://apidevtools.org/img/logos/card.png
  - scope:
      path: "test/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
